# Generated by Django 3.1.6 on 2021-02-14 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('itemCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_category', to='core.itemcategory')),
            ],
            options={
                'unique_together': {('itemCategory', 'itemName')},
            },
        ),
    ]
